// Libraries.
import type { Metadata } from "next";
// Fonts.
import { Roboto_Mono } from "next/font/google";
// Components.
import { Header } from "./components/shared/Header/Header";
import { FooterSwitcher } from "./components/shared/Footer/Footer";
// Styles.
import "./styles/globals.css";
import "./features/styles-features.css";
import "./components/AnimatedGrid/styles.css";

const roboto = Roboto_Mono({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className}  min-w-screen h-[100%]`}>
        <Header />
        {children}
        <FooterSwitcher />
      </body>
    </html>
  );
}
